name = "locphucode"
main = "workers-site/index.js"
compatibility_date = "2023-10-30"

[site]
bucket = "./out"

# Remove routes for now - they require domain setup
# [[routes]]
# pattern = "*"
# zone_name = "locdo.tech"
