# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - locdo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c95036ff14cf4ae1b5d93a4d6d5d9f08 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e2cacfcd8b4f4e88a4ff438d7be80104 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c95036ff14cf4ae1b5d93a4d6d5d9f08 }}/doxuanloc2016/locdo.tech:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'locdo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2c6c5935c05940228db6c6965105570b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c95036ff14cf4ae1b5d93a4d6d5d9f08 }}/doxuanloc2016/locdo.tech:${{ github.sha }}'